[project]
name = "swishnet-pytorch"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
]

[dependency-groups]
dev = [
    "pytest",
]

[tool.uv.sources]
torch = [{ index = "pytorch-rocm" }]

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm7.2"
